const Block = require('../models/persistence-models/block');
const Brand = require('../models/persistence-models/brand');
const Campaign = require('../models/persistence-models/campaign');
const Category = require('../models/persistence-models/category');
const Country = require('../models/persistence-models/country');
const Like = require('../models/persistence-models/like');
const Notification = require('../models/persistence-models/notification');
const Product = require('../models/persistence-models/product');
const Report = require('../models/persistence-models/report');
const SearchHistory = require('../models/persistence-models/search-history');
const Size = require('../models/persistence-models/size');
const User = require('../models/persistence-models/user');
const UserSetting = require('../models/persistence-models/user-setting');
const Conversation = require('../models/persistence-models/conversation');
const Message = require('../models/persistence-models/message');
const UserOrderAddress = require('../models/persistence-models/user-order-address');
const Device = require('../models/persistence-models/device');

exports.initGlobalModels = () => {
  global.Block = Block;
  global.Brand = Brand;
  global.Campaign = Campaign;
  global.Category = Category;
  global.Country = Country;
  global.Like = Like;
  global.Notification = Notification;
  global.Product = Product;
  global.Report = Report;
  global.SearchHistory = SearchHistory;
  global.Size = Size;
  global.User = User;
  global.UserSetting = UserSetting;
  global.Conversation = Conversation;
  global.Message = Message;
  global.UserOrderAddress = UserOrderAddress;
  global.Device = Device;
};
